In [7]:
import numpy as np

def train_on_single_example(self, example, y):
    predict = int(example @ self.w + self.b > 0)
    error = y - predict
    self.w += error * example
    self.b += error
    return error


[1.  1.  0.3]
[1.  1.  0.3]
[ 0.   0.3 -0.5]


IndexError: index 3 is out of bounds for axis 0 with size 3

In [4]:
import numpy as np

w = np.array([1, -1, 2])
b = np.array([2, 1, 0])

def vectorized_forward_pass(input_matrix):
    result = input_matrix @ w + b
    with np.nditer(result, op_flags=['readwrite']) as it:
        for x in it:
            x[...] = 1 if x > 0 else 0
    return result

print(vectorized_forward_pass(input_matrix=np.array([2, 2, 2])))

[1 1 1]
